Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,13 +12,19 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
+      - name: Debug JSON File
+        run: ls -lah stream.json || echo "stream.json not found!"
+
       - name: Send JSON Data to First URL
         run: |
-          curl -X POST "https://user:https://:A4a1FQycTdGAmo7ST6w0dw@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:8DvJ75BcS1ucPwz-OwXKWQ/streams/AQAAAMxroRRET0NRgiZPShc1GWIAAAAA" \
+          curl -X POST "https://tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:8DvJ75BcS1ucPwz-OwXKWQ/streams/AQAAAAwWBV_Lv0xMuvFRxfLBumcAAAAA" \
+          -u "user:PRcIiK_UTXuQb4D4xwyhzg" \
+          -H "Content-Type: application/json" \
           --data-binary @stream.json
 
       - name: Send JSON Data to Second URL
         run: |
-          curl -X POST "https://user:https://:PRcIiK_UTXuQb4D4xwyhzg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:8DvJ75BcS1ucPwz-OwXKWQ/streams/AQAAAAwWBV_Lv0xMuvFRxfLBumcAAAAA" \
+          curl -X POST "https://tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:8DvJ75BcS1ucPwz-OwXKWQ/streams/AQAAAMxroRRET0NRgiZPShc1GWIAAAAA" \
+          -u "user:A4a1FQycTdGAmo7ST6w0dw" \
           -H "Content-Type: application/json" \
           --data-binary @stream.json
